### ISSUE TITLE
Edit the movement function (avoidance of walls)

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#12]
Please write a function "movement" where ants move around a field (the ants have an x and y coordinate).

**Comment by lucasthierry17** [comment]
This file is a simple implementation of the movement of ants. 
See this link for the file: https://github.com/lucasthierry17/Ant_Project/blob/lucas/dummy_files/def_movement.py

**Comment by nickno7** [comment]
Well done! It's exactly what we were looking for. I think it's a very good first implementation of the ants movement and everything works for me.

**Comment by lucasthierry17** [comment]
Once the ants enter a region close to the wall, they turn around and continue their path, see code in lucas branch Version1.py
