### ISSUE TITLE
Runtime optimization

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#16]
Please look through the code we currently have and try to optimize it. Look for unnecessary loops or any library which makes the code run faster. You can find the current code here: https://github.com/lucasthierry17/Ant_Project/blob/nick/dummy_files/main.py

**Comment by lucasthierry17** [comment]
I implemented a different logic and used some pygame build in functions. Code works fine now with a couple hundred ants, I have not tested the upper limit yet. Go to https://github.com/lucasthierry17/Ant_Project/blob/follow_phero/Phero.py in order to see the code.

**Comment by nickno7** [comment]
That really helped our code run smoother and with the possibility to place more ants, while the simulation is still running fast. Thank you!
