### ISSUE TITLE
Decay of home pheromones

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#35]
Please modify the code so that the pheromones decay after a certain time and the screen turns black again.

**Comment by lucasthierry17** [comment]
I have implemented a decay for the home pheromones. The maximum value of the pheromones is 255 the minimum is 0. The value in our array determines the visibility of the blue color. The color is set to (0, 0, 255). Please try the code and also vary with the decay steps and the size of the pixels.

**Comment by Fouad1806** [comment]
Sounds good but maybe we need to implement something like a backend pheromone as well?

**Comment by lucasthierry17** [comment]
What specific idea do you have about that? A second array?

**Comment by lucasthierry17** [comment]
Discussed the method in teams. The array is being updated with a decay_rate. See the code under the main branch / source /main.py
