### ISSUE TITLE
Follow the minimal pheromone value 

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#36]
Please adjust the movement function or create a new one, so that the ants follow the pheromones, for their way home and their way to the food. Remember that the ants cannot just go after the highest value of pheromones, because then they would just follow each other.

**Comment by Fouad1806** [comment]
`def find_min_pheromone(self, ant_position, pheromones, radius):
        x, y = ant_position
        x, y = int(x), int(y)  # Convert to integers
        min_pheromone = float('inf')
        min_pheromone_position = None

        for i in range(max(0, x - radius), min(logical_width, x + radius + 1)):
            for j in range(max(0, y - radius), min(logical_height, y + radius + 1)):
                if pheromones[i, j] < min_pheromone:
                    min_pheromone = pheromones[i, j]
                    min_pheromone_position = np.array([i, j])

        return `min_pheromone_position``

So I tried to implement the follow_pheromone function but Somehow the ants all gather together to the topleft corner of the window...

**Comment by lucasthierry17** [comment]
This is caused because you are looking for the minimal value of the logical_width und logical_height, which is the screen. The top left corner has a (width, height) value of (0, 0), this is why the ants are moving this direction.

**Comment by lucasthierry17** [comment]
We discussed the idea of following the minimal pheromone value and decided, it was not worth to continue to try. Closed for now.
