### ISSUE TITLE
Go home function

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#38]
Please adjust the code so that it meets the following requirements. If an ant detects food. It should go to the food. Then the status of the ant should be "has_food". 
Now it should go back home. Once it reached home the status "has_food" should be changed again to False. 
Work with the code in the main branch.

**Comment by nickno7** [comment]
The ants are now heading home after they've collected food. They then have the status "has_food" and spread out green pheromones. Look at #49
