### ISSUE TITLE
Draw nest

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#39]
Please implement the code so that the user sees a visualization of the nest. Please create a variable for the user, in which it can adjust the position of the nest. Remember that the size of the screen is adjustable, so do not use static number. Make the position in relation to the size of the screen.

**Comment by lucasthierry17** [comment]
I added the nest in the middle of the board, pheromones are not shown because they are drawn underneath. Please check the code for mistakes and test it. Here is the pull request for this issue: https://github.com/lucasthierry17/Ant_Project/pull/45

**Comment by svenatgithub** [comment]
Works fine.
