### ISSUE TITLE
Code Diagramm

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#4]
Please build a code diagram with different functions or classes. Think about the needs of the different functions (as in the portfolio tasks)

**Comment by Fouad1806** [comment]
Hey Guys, this is the code diagramm that might work for our project.
[Zeichenfläche 1.pdf](https://github.com/lucasthierry17/Ant_Project/files/13661778/Zeichenflache.1.pdf)

**Comment by Fouad1806** [comment]
I have also created a skeleton document which I will push in a new branch for better understanding.
