### ISSUE TITLE
Please create the runtime board

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#42]
Please test the code for runtime. We used a program in class, which shows how much time each function and part of the code takes. We would like to have this for our code. Maybe the pygame elements will have to be removed for this.

**Comment by svenatgithub** [comment]
I tested the current version of our code with:
- 100 Ants
- for 1000 rounds (to have a ending)

to run the result file, you need "snakeviz"(insalled with pip)

Result is that the code takes the most time for place_pheromone, we should maybe work on that
Cant attach the file here, look into teams

**Comment by lucasthierry17** [comment]
Saw the result file, looks good.
