### ISSUE TITLE
Ants should not go over nest

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#44]
Currently, the ants start inside the nest and walk through the nest. What we would like is that the ants do not cross the nest. Please adjust the code to meet this requirement.

**Comment by svenatgithub** [comment]
Added a beta implementation into the linked branch. its inside main.py, problem is that sometimes the ant gets stuck for a few moments, i am open for ideas. :) (Code is commented)

**Comment by lucasthierry17** [comment]
Part of the issue is that you are giving the ant a random direction once they enter the nest. Rather they should turn around and walk away from the nest. I also added that only ants with food should turn around, because it does not really matter if ants without food are walking into the nest or not. 
These are the lines of code you need. You can see the changes in my branch under the file pygame_grids.py.

distance_to_home = np.linalg.norm(np.array([x, y]) - nest_position)
                if distance_to_home < 30:
                    self.has_food[ant] = False
                    directions[ant] += 180

**Comment by lucasthierry17** [comment]
Decided to not include this implementation, because the ants should also go towards the nest.
