### ISSUE TITLE
Idea of the ant movement to follow a trail of pheromones

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#46]
We have two basic ideas: 
- we could write a function, which takes in the pheromones boards. Depending on the status of the ant, it looks for the minimum value (except of 0) in the board around its position and takes a step to the direction towards this place.
- our second idea is basically like the first one, the only difference is, that we are looking for the maximum value.

**Comment by lucasthierry17** [comment]
I thought about both ideas and I think the chances are not very high to get a good visualization with these ideas. I thought about introducing a distance to the nest, ants who are looking for food should go in the direction that makes the distance bigger and ants who are trying to go home should head into the direction to make the distance smaller. 
Another idea would be to adapt the values of the pheromones, so that fresh pheromones would still be smaller than old ones. Please let me you know if you any other ideas that might work.

**Comment by Fouad1806** [comment]
I have a good idea how we can ensure that the ants follow the phreomones. We are talking about the Travelling Salesman Algorhythm or the Lin kernighan Algorythm with which this could work

**Comment by lucasthierry17** [comment]
We decided for the visual approach and discussed it again in our teams meeting
