### ISSUE TITLE
Choose ranges for the values and optimize code quality

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#48]
In the beginning, we are initializing a lot of different variables. Please test the code with different combinations of these variables and write your recommended values behind the variables. As an example, write behind the decay rate: 1 - 5, works best with 3 or something like this. It ensures nobody changes variables to some value, for which the code is not working.

**Comment by nickno7** [comment]
We tested the code with different parameters. We also included the screen where the user can input the parameters for the number of ants and their speed. There is an info in which ranges the parameters should be.
