### ISSUE TITLE
Fix Workflow

### ISSUE THREAD

**Issue by lucasthierry17** [lucasthierry17/Ant_Project#6]
Please fix the workflow, some test failed :(

**Comment by lucasthierry17** [comment]
Even tough there is still a red x, the workflow has been fixed. The current error occurs because we do not have anything in the test function, so it fails at that point. Once we write our first test function, we can have another look at the workflow, for now, everything should be good!

**Comment by lucasthierry17** [comment]
Whats the status on this issue? @svenatgithub

**Comment by svenatgithub** [comment]
Done!
